swagger: "2.0"
info:
    description: Shed your blood for the greater good...
    version: "0.0.2"
    title: Dice Cultist API
consumes:
    - application/x-www-form-urlencoded
produces:
    - application/json

basePath: /api

paths:
    /backronym/prep:   # /bk-prep
        post:
            operationId: backronym.prep
            tags:
                - Backronyms
            summary: Starts a game of backronyms!
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/start:  # /bk-start
        post:
            operationId: backronym.start
            tags:
                - Backronyms
            summary: Begins a game of Backronyms! Only usable by the host once players have joined.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/players: #/bk-getPlayers
        post:
            operationId: backronym.getPlayers
            tags:
                - Backronyms
            summary: Gets a list of active players for the current game.
            parameters:
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/score:  # /bk-getScore   [[eph]]
        post:
            operationId: backronym.getScore
            tags:
                - Backronyms
            summary: Gets the user's score.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/join:   # /bk-join
        post:
            operationId: backronym.join
            tags:
                - Backronyms
            summary: Joins the player to the current game.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
                - name: response_url
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/help:   # /bk-help    [[eph]]
        post:
            operationId: backronym.help
            tags:
                - Backronyms
            summary: Prints help information to the player.
            parameters:
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/set/word: #/bk-setWord [WORD]
        post:
            operationId: backronym.setWord
            tags:
                - Backronyms
            summary: Sets the word for the round if you are the host.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: text
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/set/phrase: #/bk-setPhrase [Insert a PHRASE]
        post:
            operationId: backronym.setPhrase
            tags:
                - Backronyms
            summary: Sets the phrase for the round if you are the host.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: text
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/set/answer: #/bk-setAnswer [Insert Your Answer] [[eph]]
        post:
            operationId: backronym.setAnswer
            tags:
                - Backronyms
            summary: Sets the your answer if you are a contestant.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: text
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
                - name: response_url
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/answers: #/bk-getAnswers
        post:
            operationId: backronym.getAnswers
            tags:
                - Backronyms
            summary: Provides all the answers given for this round. Only usable once all answers are sent in.
            parameters:
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/word:   # /bk-getWord   [[eph]]
        post:
            operationId: backronym.getWord
            tags:
                - Backronyms
            summary: Gets the word or phrase that has been set for this round.
            parameters:
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/nudge:  # /bk-nudge
        post:
            operationId: backronym.nudge
            tags:
                - Backronyms
            summary: Pings players that have yet to provide an answer this round. Only usable by the host.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/pick:   # /bk-pick [@user]
        post:
            operationId: backronym.pickWinner
            tags:
                - Backronyms
            summary: Picks the winner for this round. Only usable by the host.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: text
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
    /backronym/quit:   # /bk-quit
        post:
            operationId: backronym.dropOut
            tags:
                - Backronyms
            summary: Removes the activating player from the game.
            parameters:
                - name: user_id
                  in: formData
                  required: True
                  type: string
                - name: token
                  in: formData
                  required: True
                  type: string
            responses:
                200:
                    description: Successfully authenticated.
